### ISSUE TITLE
"You could try this commod" Spell mistake

### ISSUE THREAD

**Issue by RetronEletron** [HougeLangley/cutefishos-overlay#2]
Hello i would like to update the word "Commod" does not exist in the English language i  think you meant rather this.

"You could try those commands on your Gentoo install to enable this overlay.

Or

"You could try those commands below on your Gentoo install to enable this overlay.

**Comment by HougeLangley** [comment]
Thanks, I will fix this thing

**Comment by HougeLangley** [comment]
Thanks, problem solved.
