### ISSUE TITLE
sys-libs/libcutefish-0.7 Fails to compile as well as -9999

### ISSUE THREAD

**Issue by RetronEletron** [HougeLangley/cutefishos-overlay#21]
Log:
https://pastebin.com/mYeM9Ca9

**Comment by HougeLangley** [comment]
Maybe wait for next version releases

**Comment by HougeLangley** [comment]
Keep it open, THAX

**Comment by HougeLangley** [comment]
I have been sent issue, but no comment for now.

https://github.com/cutefishos/libcutefish/issues/13

**Comment by HougeLangley** [comment]
https://github.com/cutefishos/libcutefish/pull/11

Fixed

**Comment by HougeLangley** [comment]
I will fix it, keep open

**Comment by HougeLangley** [comment]
Done, Have a try.

**Comment by ghost** [comment]
![Screenshot_20220325_232721](https://user-images.githubusercontent.com/84268650/160214344-19d56e74-76c0-4239-9f60-fe5dc2cf3c0b.png)
Been working great here!
