### ISSUE TITLE
libcutefish-0.7 fails to compile

### ISSUE THREAD

**Issue by RetronEletron** [HougeLangley/cutefishos-overlay#3]
Log:
https://pastebin.com/cmNuFdSg

Edit:
libcutefish-9999 seems to be working but that is still something to look into.

**Comment by HougeLangley** [comment]
I got it, wait for me get home.

**Comment by HougeLangley** [comment]
@RetronEletron THANKS😀

**Comment by RetronEletron** [comment]
No problem :)
