### ISSUE TITLE
cutefish-base/cutefish-appmotor needs libsystemd

### ISSUE THREAD

**Issue by l0l67** [HougeLangley/cutefishos-overlay#4]
Hello, cutefish-base/cutefish-appmotor wont emerge, it throws an error wich complains about libsystemd missing.
I am on openrc and already tried to install libsystemd via an overlay but that did not solve it.

What could i try to solve this?

**Comment by HougeLangley** [comment]
Thanks for your reply, I will add a USE flag, you could "-" this one.

**Comment by HougeLangley** [comment]
wait for me a moment 😀
